// Article pages deliberately shipped without part of the opening summary
// (src/components/article/ArticleSummary.astro). The article route checks
// every page in src/config/article-pages.ts at build time: a page without a
// Quick Answer, or without its key-points list ("Here’s What This Means for
// You:"), fails the build unless it is listed here with the reason. A listed
// page that has the element fails too, so a hold is removed with its fix.
// The A–Z hubs use a guide summary instead (src/config/hub-nav.ts).

/** No Quick Answer yet. The FLAG pages of the October 2026 Quick Answer audit:
 * the article contradicts itself on its main question, so a faithful answer
 * needs Randy to resolve the conflict first (CLAUDE.md, "Quick Answers"). */
export const QUICK_ANSWER_HELD: Record<string, string> = {
  "/aflac-burial-insurance-review/":
    "The opening paragraph a Quick Answer would come from says most people don’t qualify for the level (top tier) plan and get pushed into graded or modified plans, while the key points say underwriting is fairly lenient so many people will qualify for the best rates. Randy to resolve before a Quick Answer is added.",
  "/baltimore-life-burial-insurance-review/":
    "The page contradicts itself on the points a Quick Answer would lead with: price (more expensive vs average vs not expensive), whether there is any reduced-benefit period (Silver Guard II graded schedule vs FAQ “does not have a waiting period”), coverage size (Silver Guard maximums of $15,000–$25,000 vs FAQ minimum $50,000 and up to $1,000,000), and financial rating (A- vs B++). The FAQ appears to be generic text that doesn’t match the article.",
  "/buyers-guide/": "Held by Randy (October 2026).",
  "/mutual-of-omaha-burial-insurance/": "Held by Randy (October 2026).",
  "/elks-lodge-life-insurance-options/":
    "Second verification pass (Oct 8 2026) still cannot establish whether current Elks membership gives access to any life insurance partner program. National level: elksbenefits.com (the 'Elks Member Benefit Center', described by elks.org lodge pages as a member benefit program offering auto and home insurance, travel, wireless and prescription savings that supports the BPOE) has insurance pages listing The Hartford guaranteed-acceptance senior life program, United of Omaha guaranteed-acceptance whole life (ages 45-85, up to $25,000), The Family Security Plan (whole/term life, accident; 'since 1973') and American Senior Benefits; but search metadata dates the life pages about seven years old, and no elks.org/Grand Lodge page found confirms that site's operator, its current insurance partners or terms (elks.org and elksbenefits.com could not be fetched directly; DNS/proxy blocked). Grand Lodge: only lodge-level programs (liability, property, crime) and an employee dental plan (Lincoln Financial) were found; neither is member life insurance. The Elks Magazine life insurance article (July/August 2021) is general education, not an Elks plan. State associations and local lodges: no member life insurance programs found (state Elks insurance programs found cover lodges). So the article's body/FAQ claim 'does not partner with any insurance company' is contradicted by the member-benefit site, while the intro's 'partners with programs ... at group rates' cannot be confirmed as current. Missing evidence: a current elks.org / Grand Lodge member-benefits page (or Grand Secretary notice) naming any current life or accident insurance partner and terms, or confirmation from the Grand Lodge (Chicago) that the elksbenefits.com insurance listings are current. No edits made to the article.",
  "/security-national-burial-insurance-review/":
    "The two official 2025 PDFs could not be opened in this session: securitynationallife.com is blocked by the egress proxy (curl: CONNECT 403; WebFetch: DNS failure), so the central facts could not be read from the PDFs themselves. WebSearch index extracts restricted to securitynationallife.com (not verbatim, no page numbers) consistently say: 2025 handbook (effective 1/1/2025) and the 2023/May 2025 overviews name the plan the Loyalty Plan; Preferred and Standard pay the full face amount from day one; Modified = return of premium + 10% for the first 2 years, full benefit after the 2nd year; ages 40-90 (Modified to 85); $2,500-$50,000; Preferred 40-75 up to $50,000, Standard and Modified 40-75 up to $25,000. The 25/50/75/100 graded schedule belongs to a separate Security National 'Guardian' plan, not the Loyalty Plan. Still unresolved: (1) how an accidental death is paid during the Modified plan's first two years (extracts show ADB rider tables 'Year 1-2' in the 2022 guide and 'Year 1-3' in the 2025 handbook, product unclear); (2) state variations (extracts: riders not available in all states; no Loyalty-specific state list found); (3) a 'Final Expense Product Overview Legal_Spanish_JULY 2025' download exists, so an English July 2025 overview may supersede the May 2025 one. To release: Randy (or a session with access) opens the two PDFs and confirms the Modified benefit wording, the ADB/Modified interaction, the Preferred $50,000 maximum and any newer overview; then the draft Quick Answer can be used unchanged if those match.",
  "/senior-legacy-vs-senior-legacy-life/":
    "Second verification pass (Oct 8 2026): the two identities are now clearer but the article still cannot be corrected safely. (1) seniorlegacylife.com ('Senior Legacy Life'): its own homepage says it is a branded referral network and dba of MJ Ventures LLC, does not sell insurance, and is not an insurance company or agency (verified; matches the owner's view and /senior-legacy-life-review/). (2) seniorlegacy.com ('Senior Legacy', also branded 'Ensured Life Insurance'): its own site says 'Senior Legacy Life Insurance, LLC is not a life insurance company, we are a life insurance agency', independently owned, headquartered in Lexington, KY, owner Christopher Stinnett, agents licensed by their states; a Kentucky company directory lists 'Senior Legacy LLC', Lexington, registered March 14, 2023, active, registered agent Chris Stinnett. Its insurance licensing was NOT confirmed on a regulator source (Kentucky DOI / NIPR / Kentucky SOS were not reachable), and the directory name differs slightly from the agency's legal name. (3) The article's 'Senior Legacy' content (postcards/mailers, the Robert client story, 'lead vendor' and 'sales agency' labels) is not tied to either entity: no evidence shows which business sends 'Senior Legacy' mailers. Rewriting the page as 'licensed Lexington agency vs referral network' would rest on the agency's self-description only and could wrongly attach the mailer story to a named Kentucky agency, while the current text (body: Senior Legacy Life is a licensed NAIC agency; intro: both are lead generators) is wrong about seniorlegacylife.com. Missing evidence: Kentucky DOI or NIPR agency license record for Senior Legacy Life Insurance, LLC / Senior Legacy LLC; Kentucky SOS record; and Randy's confirmation of which 'Senior Legacy' (mailer sender) the article and the Robert story refer to. No edits made. /senior-legacy-life-review/ was rechecked and is consistent (it describes only seniorlegacylife.com, as a referral network dba of MJ Ventures LLC, and no longer mentions Senior Life Insurance Company of Thomasville, GA in visible text); no change needed.",
};

/** No key-points list: the article has none to show. */
export const SUMMARY_HELD: Record<string, string> = {
  "/buyers-guide/":
    "The article has no key-points list (\"Here’s the Bottom Line\") to show; adding one needs new copy Randy approves.",
};
