// Article pages whose legacy opening paragraph(s) the Quick Answer replaces
// (October 2026 audit): the paragraph restates the Quick Answer and key
// points, and everything it says is also on the page. Listed by the
// paragraph's opening words; ArticleLayout leaves those paragraphs out
// (src/lib/article/enhance.ts) and the Markdown source keeps them. The build
// fails when an opening is no longer found, or the page has no Quick Answer.
export const LEGACY_INTROS: Record<string, readonly string[]> = {
  '/5-reasons-you-should-be-worried-about-aarp-life-insurance/': ["AARP life insurance is marketed as simple and easy,"],
  '/5-ways-to-get-burial-insurance-with-first-day-coverage/': ["Getting burial insurance with first-day coverage isn’t luck. It’s"],
  '/aarp-burial-insurance-review/': ["AARP burial insurance is marketed as simple and safe,"],
  '/aarp-life-insurance-review/': ["AARP life insurance sounds simple, but it comes with"],
  '/american-legion-life-insurance/': ["American Legion member life insurance sounds like a solid"],
  '/americo-life-insurance-quit-smoking-advantage/': ["Americo’s Quit Smoking Advantage is a type of final"],
  '/big-lou-term-life-insurance-review/': ["Big Lou life insurance is really a brokerage using"],
  '/burial-insurance-breast-cancer/': ["Getting burial insurance with breast cancer depends heavily on", "!!! READ THIS FIRST & WATCH VIDEO BELOW !!!", "In this article, you will find out precisely how"],
  '/burial-insurance-calculator/': ["A burial insurance calculator helps you estimate how much"],
  '/burial-insurance-with-lung-cancer/': ["Getting burial insurance with lung cancer depends almost entirely", "IS FIRST & WATCH VIDEO BELOW !!! Current Cancer", "If you’re looking for life insurance after lung cancer,"],
  '/burial-insurance/': ["Burial insurance is a type of whole life insurance"],
  '/burial-insurance/adl-activities-of-daily-living/': ["Burial insurance with ADL (Activities of Daily Living) limitations", "!!! READ THIS FIRST !!! If you need help", "If you or a loved one currently needs help"],
  '/burial-insurance/american-amicable-life-insurance-review/': ["American Amicable life insurance is known for being easy"],
  '/burial-insurance/asthma/': ["Getting burial insurance with asthma is usually easier than"],
  '/burial-insurance/autism/': ["Getting burial insurance with autism depends on how the"],
  '/burial-insurance/bipolar-disorder/': ["Getting burial insurance with bipolar disorder depends on how"],
  '/burial-insurance/blind/': ["Burial insurance for the blind is more accessible than"],
  '/burial-insurance/blood-thinner/': ["Burial insurance for blood thinner users is more flexible"],
  '/burial-insurance/borrowing-against-cash-value/': ["Borrowing against cash value pros and cons come down"],
  '/burial-insurance/build-chart/': ["A life insurance build chart is a height-and-weight guideline"],
  '/burial-insurance/burial-insurance-application-process/': ["The final expense insurance application process is straightforward, but"],
  '/burial-insurance/burial-insurance-arthritis/': ["Getting burial insurance with arthritis is usually easier than"],
  '/burial-insurance/burial-insurance-with-gout/': ["Burial insurance with gout is one of the easier"],
  '/burial-insurance/can-i-buy-life-insurance-on-my-mother/': ["Yes, you can buy life insurance on your mother,"],
  '/burial-insurance/cardiomyopathy/': ["Getting burial insurance with cardiomyopathy depends heavily on how"],
  '/burial-insurance/cerebral-palsy/': ["Getting burial insurance with cerebral palsy depends on how"],
  '/burial-insurance/contestability-period/': ["The burial insurance contestability period is usually the first"],
  '/burial-insurance/copd/': ["Getting burial insurance with COPD comes down to how"],
  '/burial-insurance/cystic-fibrosis/': ["Getting burial insurance with cystic fibrosis comes down to"],
  '/burial-insurance/depression/': ["Getting burial insurance with depression is usually much easier"],
  '/burial-insurance/diabetes/': ["Getting burial insurance with diabetes is very doable, but"],
  '/burial-insurance/diabetic-coma/': ["Getting burial insurance with a diabetic coma history is"],
  '/burial-insurance/diabetic-nephropathy/': ["Getting final expense insurance with diabetic nephropathy depends on"],
  '/burial-insurance/disabled-persons/': ["Burial insurance for disabled persons is more accessible than"],
  '/burial-insurance/emphysema/': ["Getting burial insurance with emphysema depends on how advanced"],
  '/burial-insurance/epilepsy-seizures/': ["Getting burial insurance with epilepsy or seizures depends heavily"],
  '/burial-insurance/esophageal-cancer/': ["Getting burial insurance with esophageal cancer depends almost entirely"],
  '/burial-insurance/fibromyalgia/': ["Getting burial insurance with fibromyalgia is usually easier than"],
  '/burial-insurance/final-expense-insurance-for-pastors-and-congregations/': ["Final expense insurance for pastors and congregations is a"],
  '/burial-insurance/heart-attack/': ["Getting burial insurance after a heart attack comes down"],
  '/burial-insurance/heart-bypass-surgery/': ["Burial insurance after heart bypass surgery depends almost entirely"],
  '/burial-insurance/heart-conditions/': ["Getting burial insurance with heart conditions depends on what"],
  '/burial-insurance/heart-disease/': ["Getting burial insurance with heart disease comes down to"],
  '/burial-insurance/heart-murmur/': ["Getting burial insurance with a heart murmur depends on"],
  '/burial-insurance/heart-surgery-2/': ["Getting burial insurance after heart surgery depends heavily on"],
  '/burial-insurance/heart-surgery/': ["Getting burial insurance after heart surgery depends heavily on"],
  '/burial-insurance/hepatitis-b/': ["Getting burial insurance with Hepatitis B depends on how"],
  '/burial-insurance/hepatitis-c/': ["Getting burial insurance with Hepatitis C depends on your"],
  '/burial-insurance/hodgkins-disease/': ["Getting burial insurance with Hodgkin’s disease depends heavily on"],
  '/burial-insurance/how-to-apply-for-burial-insurance/': ["The process for applying for burial insurance is straightforward,"],
  '/burial-insurance/is-burial-insurance-permanent/': ["Burial insurance is permanent coverage, not temporary. It’s a"],
  '/burial-insurance/kidney-disease/': ["Getting burial insurance with kidney disease depends on how"],
  '/burial-insurance/life-insurance-no-exam/': ["Final expense life insurance with no exam is a"],
  '/burial-insurance/life-insurance-widows/': ["Final expense life insurance for widows is designed to"],
  '/burial-insurance/life-insurance-with-no-waiting-period/': ["Life insurance with no waiting period is usually simplified"],
  '/burial-insurance/marijuana-use/': ["Getting burial insurance with marijuana use is usually easier"],
  '/burial-insurance/medical-marijuana/': ["Using medical marijuana doesn’t block you from getting burial"],
  '/burial-insurance/mental-health-conditions/': ["Getting burial insurance with mental health conditions is usually"],
  '/burial-insurance/multiple-sclerosis/': ["Burial insurance with multiple sclerosis is still possible, but"],
  '/burial-insurance/no-questions-asked/': ["“Burial insurance no questions asked” sounds easy, but it"],
  '/burial-insurance/on-someone-else/': ["Buying burial insurance on someone else is possible, but"],
  '/burial-insurance/online/': ["Buying burial insurance online is quick and convenient, but"],
  '/burial-insurance/ovarian-cancer/': ["Getting burial insurance with ovarian cancer depends almost entirely"],
  '/burial-insurance/pancreatic-cancer/': ["Getting burial insurance with pancreatic cancer is extremely limited"],
  '/burial-insurance/parents/': ["Burial insurance for parents is a type of whole"],
  '/burial-insurance/parkinsons-disease/': ["Getting burial insurance with Parkinson’s disease comes down to"],
  '/burial-insurance/peripheral-vascular-disease-pvd-pad/': ["Burial insurance with peripheral vascular disease (PVD or PAD)"],
  '/burial-insurance/prion-disease/': ["Prion disease is one of the most severe conditions", "!!! READ THIS FIRST !!! Most life insurance companies", "If you or a member of your family has"],
  '/burial-insurance/ptsd/': ["Burial insurance with PTSD is more available than most"],
  '/burial-insurance/respiratory-lung-conditions/': ["Getting burial insurance with respiratory and lung conditions depends"],
  '/burial-insurance/sarcoidosis/': ["Getting burial insurance with sarcoidosis depends on how serious"],
  '/burial-insurance/sarcoma/': ["Getting burial insurance with sarcoma depends almost entirely on"],
  '/burial-insurance/scams/': ["Burial insurance scams usually come down to confusion and"],
  '/burial-insurance/schizophrenia/': ["Burial insurance with schizophrenia is more available than most"],
  '/burial-insurance/scleroderma/': ["Burial insurance with scleroderma is more available than most"],
  '/burial-insurance/sister/': ["Burial insurance for a sister is possible, but there"],
  '/burial-insurance/skin-cancer/': ["Getting burial insurance with skin cancer depends on the"],
  '/burial-insurance/state-regulated-life-insurance/': ["State regulated life insurance is just a marketing phrase,"],
  '/burial-insurance/stroke-tia/': ["Getting burial insurance after a stroke or TIA depends"],
  '/burial-insurance/testicular-cancer/': ["Getting burial insurance with testicular cancer depends heavily on"],
  '/burial-insurance/toileting-activities-of-daily-living-adl/': ["Burial insurance with help for toileting ADL is one", "!!! READ THIS FIRST !!! If you need help", "Here’s a detailed guide on what you need to"],
  '/burial-insurance/with-first-day-coverage/': ["Burial insurance with first-day coverage is a type of"],
  '/ethos-life-insurance-review/': ["Ethos Life Insurance is an online platform that helps"],
  '/family-benefit-life-burial-insurance-review/': ["Family Benefit Life burial insurance is a type of"],
  '/fidelity-life-burial-insurance-review/': ["Fidelity Life burial insurance is a whole life policy"],
  '/final-expense-life-insurance-complete-guide/': ["Final expense life insurance is a type of whole"],
  '/final-expense-life-insurance-diabetics/': ["Getting final expense life insurance for diabetics is more"],
  '/final-expense-life-insurance-over-80/': ["Final expense life insurance over 80 is usually your"],
  '/foresters-burial-insurance-review/': ["Foresters burial insurance is a type of whole life"],
  '/gerber-life-insurance-review/': ["Gerber Life Insurance is known for simple approval and"],
  '/guarantee-trust-life-insurance-review/': ["Guarantee Trust Life burial insurance is a whole life"],
  '/how-much-burial-insurance-do-i-need/': ["How much burial insurance you need depends on what"],
  '/iul-book/iul-military-members-veterans/': ["Indexed universal life insurance for military members and veterans"],
  '/iul-book/iul-police-officers-firefighters/': ["Indexed Universal Life insurance sounds like a smart mix"],
  '/iul-book/iuls-for-truckers/': ["IULs for truckers sound attractive because they mix life"],
  '/iul-book/teachers-indexed-universal-life-iul/': ["Indexed universal life insurance for teachers sounds appealing, especially"],
  '/liberty-bankers-burial-insurance-review/': ["Liberty Bankers’ burial insurance is a type of whole"],
  '/life-insurance-for-employees/': ["Life insurance for employees is usually called group life"],
  '/open-care-life-insurance-review/': ["Open Care life insurance is a marketing platform that"],
  '/phoenix-life-burial-insurance-review-pros-cons/': ["Phoenix Life burial insurance, now part of Nassau Re,"],
  '/prepaid-caskets-pros-and-cons/': ["Prepaid caskets are part of a prepaid funeral plan"],
  '/prepaid-funeral/': ["Prepaid funeral plans let you pay a funeral home"],
  '/primerica-life-insurance-review/': ["Primerica life insurance focuses almost entirely on term life"],
  '/prosperity-life-burial-insurance-review-pros-cons/': ["Prosperity Life burial insurance is a type of whole"],
  '/senior-life-insurance-review/': ["Senior Life Insurance is a final-expense whole-life insurance company"],
  '/term-life-insurance-doctors/': ["Term life insurance for doctors needs to match income,"],
  '/term-life-insurance-guide-everyone/': ["Term life insurance is the simplest type of life"],
  '/term-life-insurance-truckers/': ["Term life insurance for truckers is usually the smartest"],
  '/the-importance-of-burial-insurance/': ["Burial insurance exists for one reason. To keep your"],
  '/transamerica-burial-insurance-review/': ["Transamerica burial insurance can work, but only in the"],
  '/what-happens-when-your-spouse-died-no-life-insurance/': ["When your spouse dies without life insurance, the financial"],
  '/burial-insurance-substance-abuse-drug-abuse/': ["Burial insurance with substance abuse or drug abuse depends"],
  '/burial-insurance/final-expense-life-insurance-dave-ramsey/': ["Many people want to know what Dave Ramsey says"],
  '/burial-insurance/lupus/': ["You can still get burial insurance with lupus, and no"],
  '/burial-insurance/transferring-activities-of-daily-living-adl/': ["Transferring means moving yourself between your bed, a chair,"],
  '/final-expense-life-insurance-retired-truckers/': ["Final expense life insurance for retired truckers is usually easier"],
  '/term-life-conversion-to-whole-life/': ["Term life conversion to whole life lets you convert a"],
};
