// Article pages whose legacy opening paragraph(s) the Quick Answer replaces
// (October 2026 audit): the paragraph restates the Quick Answer and key
// points, and everything it says is also on the page. Listed by the
// paragraph's opening words; ArticleLayout leaves those paragraphs out
// (src/lib/article/enhance.ts) and the Markdown source keeps them. The build
// fails when an opening is no longer found, or the page has no Quick Answer.
export const LEGACY_INTROS: Record<string, readonly string[]> = {
  '/5-reasons-you-should-be-worried-about-aarp-life-insurance/': ["AARP life insurance is marketed as simple and easy,"],
  '/5-ways-to-get-burial-insurance-with-first-day-coverage/': ["Getting burial insurance with first-day coverage isn’t luck. It’s"],
  '/aarp-burial-insurance-review/': ["AARP burial insurance is marketed as simple and safe,"],
  '/aarp-life-insurance-review/': ["AARP life insurance sounds simple, but it comes with"],
  '/aetna-burial-insurance-review/': ["Aetna burial insurance is a whole life policy designed to"],
  '/american-legion-life-insurance/': ["American Legion member life insurance sounds like a solid"],
  '/americo-life-insurance-quit-smoking-advantage/': ["Americo’s Quit Smoking Advantage is a type of final"],
  '/big-lou-term-life-insurance-review/': ["Big Lou life insurance is really a brokerage using"],
  '/burial-insurance-breast-cancer/': ["Getting burial insurance with breast cancer depends heavily on", "!!! READ THIS FIRST & WATCH VIDEO BELOW !!!", "In this article, you will find out precisely how"],
  '/burial-insurance-calculator/': ["A burial insurance calculator helps you estimate how much"],
  '/burial-insurance-defibrillator/': ["Burial insurance with a defibrillator is still possible, but it"],
  '/burial-insurance-diabetic-complications/': ["Burial insurance with a diabetic amputation is still possible, but"],
  '/burial-insurance-kidney-failure/': ["Getting burial insurance with kidney failure is still possible, but"],
  '/burial-insurance-substance-abuse-drug-abuse/': ["Burial insurance with substance abuse or drug abuse depends"],
  '/burial-insurance-with-lung-cancer/': ["Getting burial insurance with lung cancer depends almost entirely", "IS FIRST & WATCH VIDEO BELOW !!! Current Cancer", "If you’re looking for life insurance after lung cancer,"],
  '/burial-insurance/': ["Burial insurance is a type of whole life insurance"],
  '/burial-insurance/adl-activities-of-daily-living/': ["Burial insurance with ADL (Activities of Daily Living) limitations", "!!! READ THIS FIRST !!! If you need help", "If you or a loved one currently needs help"],
  '/burial-insurance/afib/': ["Getting burial insurance with AFib comes down to how controlled"],
  '/burial-insurance/aids-hiv/': ["Burial insurance with AIDS or HIV is more available today"],
  '/burial-insurance/alcohol-or-drug-abuse/': ["Getting burial insurance with alcohol or drug abuse comes down"],
  '/burial-insurance/american-amicable-life-insurance-review/': ["American Amicable life insurance is known for being easy"],
  '/burial-insurance/and-coronavirus/': ["Burial insurance and coronavirus caused a lot of confusion, but"],
  '/burial-insurance/and-suicide/': ["Most people think life insurance won’t pay for suicide. That’s"],
  '/burial-insurance/aneurysm/': ["Getting burial insurance with an aneurysm depends on timing, treatment,"],
  '/burial-insurance/angina/': ["Burial insurance with angina depends heavily on timing and severity."],
  '/burial-insurance/arrhythmia/': ["Burial insurance with arrhythmia depends on how serious and controlled"],
  '/burial-insurance/asthma/': ["Getting burial insurance with asthma is usually easier than"],
  '/burial-insurance/autism/': ["Getting burial insurance with autism depends on how the"],
  '/burial-insurance/basal-cell-squamous-cell-carcinoma/': ["Getting burial insurance with basal cell or squamous cell carcinoma"],
  '/burial-insurance/bathing-disability-adl/': ["If you need help with bathing, that’s considered an ADL"],
  '/burial-insurance/bipolar-disorder/': ["Getting burial insurance with bipolar disorder depends on how"],
  '/burial-insurance/bladder-cancer/': ["Getting burial insurance with bladder cancer depends on your stage,"],
  '/burial-insurance/blind/': ["Burial insurance for the blind is more accessible than"],
  '/burial-insurance/blood-cancer-leukemia/': ["Getting burial insurance with leukemia or blood cancer depends heavily"],
  '/burial-insurance/blood-clot/': ["Burial insurance with a blood clot depends heavily on when"],
  '/burial-insurance/blood-thinner/': ["Burial insurance for blood thinner users is more flexible"],
  '/burial-insurance/borrowing-against-cash-value/': ["Borrowing against cash value pros and cons come down"],
  '/burial-insurance/brain-cancer/': ["Getting burial insurance with brain cancer depends on timing, treatment,"],
  '/burial-insurance/brain-tumor/': ["Getting burial insurance with a brain tumor depends on the"],
  '/burial-insurance/breast-cancer/': ["Getting burial insurance with breast cancer depends on timing, stage,"],
  '/burial-insurance/brother/': ["Getting burial insurance on your brother is possible, but there"],
  '/burial-insurance/build-chart/': ["A life insurance build chart is a height-and-weight guideline"],
  '/burial-insurance/burial-insurance-application-process/': ["The final expense insurance application process is straightforward, but"],
  '/burial-insurance/burial-insurance-arthritis/': ["Getting burial insurance with arthritis is usually easier than"],
  '/burial-insurance/burial-insurance-near-me/': ["Affordable burial insurance near you isn’t about location, it’s about"],
  '/burial-insurance/burial-insurance-with-diverticulitis/': ["Affordable burial insurance with diverticulitis depends on how stable your"],
  '/burial-insurance/burial-insurance-with-gout/': ["Burial insurance with gout is one of the easier"],
  '/burial-insurance/can-i-buy-life-insurance-on-my-mother/': ["Yes, you can buy life insurance on your mother,"],
  '/burial-insurance/cardiomyopathy/': ["Getting burial insurance with cardiomyopathy depends heavily on how"],
  '/burial-insurance/cbd-oil/': ["Burial insurance with CBD oil use is more flexible than"],
  '/burial-insurance/cerebral-palsy/': ["Getting burial insurance with cerebral palsy depends on how"],
  '/burial-insurance/cervical-cancer/': ["Getting burial insurance with cervical cancer depends on timing, stage,"],
  '/burial-insurance/chronic-bronchitis/': ["Burial insurance with chronic bronchitis depends on how serious and"],
  '/burial-insurance/cirrhosis/': ["Getting burial insurance with cirrhosis depends on how severe your"],
  '/burial-insurance/colorectal-cancer/': ["Getting burial insurance with colorectal cancer depends heavily on timing"],
  '/burial-insurance/congestive-heart-failure/': ["Getting burial insurance with congestive heart failure depends on how"],
  '/burial-insurance/contestability-period/': ["The burial insurance contestability period is usually the first"],
  '/burial-insurance/continence-activities-of-daily-living-adl/': ["Burial insurance with help for continence or other Activities of"],
  '/burial-insurance/copd/': ["Getting burial insurance with COPD comes down to how"],
  '/burial-insurance/coronary-artery-disease/': ["Getting burial insurance with coronary artery disease depends on how"],
  '/burial-insurance/crohns-disease/': ["Burial insurance with Crohn’s disease depends on how severe and"],
  '/burial-insurance/cystic-fibrosis/': ["Getting burial insurance with cystic fibrosis comes down to"],
  '/burial-insurance/dementia-alzheimers/': ["Getting burial insurance with dementia or Alzheimer’s is one of"],
  '/burial-insurance/depression/': ["Getting burial insurance with depression is usually much easier"],
  '/burial-insurance/diabetes/': ["Getting burial insurance with diabetes is very doable, but"],
  '/burial-insurance/diabetic-amputation/': ["Getting burial insurance with diabetic amputation is possible, but it’s"],
  '/burial-insurance/diabetic-coma/': ["Getting burial insurance with a diabetic coma history is"],
  '/burial-insurance/diabetic-insulin-shock/': ["Getting burial insurance after diabetic insulin shock is one of"],
  '/burial-insurance/diabetic-nephropathy/': ["Getting final expense insurance with diabetic nephropathy depends on"],
  '/burial-insurance/diabetic-neuropathy/': ["Getting burial insurance with diabetic neuropathy depends on how severe"],
  '/burial-insurance/dialysis-patients/': ["Getting burial insurance for dialysis patients is possible, but your"],
  '/burial-insurance/disability/': ["Purchasing burial insurance with a disability is not out of"],
  '/burial-insurance/disabled-persons/': ["Burial insurance for disabled persons is more accessible than"],
  '/burial-insurance/donating-your-body-to-science/': ["Donating your body to science can reduce costs, but it"],
  '/burial-insurance/down-syndrome/': ["Burial insurance for Down syndrome is possible, but it’s limited"],
  '/burial-insurance/drug-abuse-treatment/': ["Burial insurance after drug abuse treatment depends on timing and"],
  '/burial-insurance/drug-alcohol-abuse/': ["Getting burial insurance with drug or alcohol abuse depends almost"],
  '/burial-insurance/dui-dwi/': ["Burial insurance with DUI or DWI depends heavily on timing"],
  '/burial-insurance/eating-activities-of-daily-living-adl/': ["Burial insurance with help eating ADL is one of the"],
  '/burial-insurance/emphysema/': ["Getting burial insurance with emphysema depends on how advanced"],
  '/burial-insurance/endocarditis-heart-infection/': ["Getting burial insurance with endocarditis depends on how serious the"],
  '/burial-insurance/epilepsy-seizures/': ["Getting burial insurance with epilepsy or seizures depends heavily"],
  '/burial-insurance/esophageal-cancer/': ["Getting burial insurance with esophageal cancer depends almost entirely"],
  '/burial-insurance/fatty-liver-disease/': ["Getting burial insurance with fatty liver disease depends on how"],
  '/burial-insurance/felony-conviction/': ["Burial insurance with a felony conviction is more available than"],
  '/burial-insurance/fibromyalgia/': ["Getting burial insurance with fibromyalgia is usually easier than"],
  '/burial-insurance/final-expense-insurance-for-pastors-and-congregations/': ["Final expense insurance for pastors and congregations is a"],
  '/burial-insurance/final-expense-life-insurance-dave-ramsey/': ["Many people want to know what Dave Ramsey says"],
  '/burial-insurance/for-smokers/': ["Burial insurance for smokers is widely available, but it comes"],
  '/burial-insurance/funeral-insurance-for-seniors/': ["Funeral insurance for seniors is a type of whole life"],
  '/burial-insurance/graves-disease/': ["Getting burial insurance with Graves’ disease is usually easier than"],
  '/burial-insurance/guaranteed-issue-life-insurance-for-seniors/': ["Guaranteed issue life insurance for seniors is a type of"],
  '/burial-insurance/heart-attack/': ["Getting burial insurance after a heart attack comes down"],
  '/burial-insurance/heart-bypass-surgery/': ["Burial insurance after heart bypass surgery depends almost entirely"],
  '/burial-insurance/heart-conditions/': ["Getting burial insurance with heart conditions depends on what"],
  '/burial-insurance/heart-disease/': ["Getting burial insurance with heart disease comes down to"],
  '/burial-insurance/heart-failure/': ["Getting burial insurance with heart failure is possible, but your"],
  '/burial-insurance/heart-murmur/': ["Getting burial insurance with a heart murmur depends on"],
  '/burial-insurance/heart-surgery-2/': ["Getting burial insurance after heart surgery depends heavily on"],
  '/burial-insurance/heart-surgery/': ["Getting burial insurance after heart surgery depends heavily on"],
  '/burial-insurance/hepatitis-b/': ["Getting burial insurance with Hepatitis B depends on how"],
  '/burial-insurance/hepatitis-c/': ["Getting burial insurance with Hepatitis C depends on your"],
  '/burial-insurance/high-blood-pressure/': ["Burial insurance for high blood pressure is usually easier to"],
  '/burial-insurance/high-cholesterol/': ["Getting burial insurance with high cholesterol is usually easier than"],
  '/burial-insurance/hodgkins-disease/': ["Getting burial insurance with Hodgkin’s disease depends heavily on"],
  '/burial-insurance/hospice-patients/': ["Burial insurance for hospice patients is extremely limited because hospice"],
  '/burial-insurance/hospitalized/': ["Burial insurance after being hospitalized depends on how recent the"],
  '/burial-insurance/how-to-apply-for-burial-insurance/': ["The process for applying for burial insurance is straightforward,"],
  '/burial-insurance/huntingtons-disease/': ["Getting burial insurance with Huntington’s disease is one of the"],
  '/burial-insurance/insulin-diabetics/': ["Burial insurance for insulin dependent diabetics depends on how well"],
  '/burial-insurance/is-burial-insurance-permanent/': ["Burial insurance is permanent coverage, not temporary. It’s a"],
  '/burial-insurance/kidney-disease/': ["Getting burial insurance with kidney disease depends on how"],
  '/burial-insurance/leukemia/': ["Burial insurance with leukemia depends heavily on timing and your"],
  '/burial-insurance/life-insurance-for-seniors/': ["Life insurance for seniors ages 50 to 85 includes term"],
  '/burial-insurance/life-insurance-no-exam/': ["Final expense life insurance with no exam is a"],
  '/burial-insurance/life-insurance-widows/': ["Final expense life insurance for widows is designed to"],
  '/burial-insurance/life-insurance-with-no-waiting-period/': ["Life insurance with no waiting period is usually simplified"],
  '/burial-insurance/liver-disease-liver-disorder/': ["Getting burial insurance with liver disease depends on how serious"],
  '/burial-insurance/liver-disease/': ["Getting burial insurance with liver disease is possible, but your"],
  '/burial-insurance/lou-gehrigs-disease-als/': ["Getting burial insurance with ALS is very different from most"],
  '/burial-insurance/lung-cancer/': ["Getting burial insurance with lung cancer depends heavily on timing,"],
  '/burial-insurance/lung-disease/': ["Getting burial insurance with lung disease depends on how severe"],
  '/burial-insurance/lupus/': ["You can still get burial insurance with lupus, and no"],
  '/burial-insurance/marijuana-use/': ["Getting burial insurance with marijuana use is usually easier"],
  '/burial-insurance/medical-marijuana/': ["Using medical marijuana doesn’t block you from getting burial"],
  '/burial-insurance/melanoma-skin-cancer/': ["Getting burial insurance with melanoma skin cancer depends heavily on"],
  '/burial-insurance/mental-health-conditions/': ["Getting burial insurance with mental health conditions is usually"],
  '/burial-insurance/multiple-myeloma/': ["Getting burial insurance with multiple myeloma depends heavily on your"],
  '/burial-insurance/multiple-sclerosis/': ["Burial insurance with multiple sclerosis is still possible, but"],
  '/burial-insurance/muscular-dystrophy/': ["Burial insurance with muscular dystrophy depends on how advanced your"],
  '/burial-insurance/myelodysplastic-syndrome/': ["Getting burial insurance with myelodysplastic syndrome depends almost entirely on"],
  '/burial-insurance/native-americans/': ["Burial insurance for Native Americans works the same as it"],
  '/burial-insurance/need-help-with-dressing-activities-of-daily-living-adl/': ["Needing help with dressing is part of what insurers call"],
  '/burial-insurance/neurological-disorders/': ["Getting burial insurance with neurological disorders depends on how advanced"],
  '/burial-insurance/no-questions-asked/': ["“Burial insurance no questions asked” sounds easy, but it"],
  '/burial-insurance/nursing-home-residents/': ["Getting burial insurance as a nursing home resident is tough,"],
  '/burial-insurance/on-someone-else/': ["Buying burial insurance on someone else is possible, but"],
  '/burial-insurance/online/': ["Buying burial insurance online is quick and convenient, but"],
  '/burial-insurance/organ-transplant/': ["Burial insurance with an organ transplant depends heavily on timing"],
  '/burial-insurance/ovarian-cancer/': ["Getting burial insurance with ovarian cancer depends almost entirely"],
  '/burial-insurance/over-80/': ["Burial insurance over 80 is still available, but your options"],
  '/burial-insurance/overweight-obese/': ["Affordable burial insurance for overweight and obese people is more"],
  '/burial-insurance/oxygen-use/': ["Burial insurance with oxygen use is one of the toughest"],
  '/burial-insurance/pacemaker/': ["Getting burial insurance with a pacemaker is very possible, but"],
  '/burial-insurance/pancreatic-cancer/': ["Getting burial insurance with pancreatic cancer is extremely limited"],
  '/burial-insurance/paralysis-paralyzed/': ["Getting burial insurance with paralysis is possible, but your options"],
  '/burial-insurance/parents/': ["Burial insurance for parents is a type of whole"],
  '/burial-insurance/parkinsons-disease/': ["Getting burial insurance with Parkinson’s disease comes down to"],
  '/burial-insurance/peripheral-vascular-disease-pvd-pad/': ["Burial insurance with peripheral vascular disease (PVD or PAD)"],
  '/burial-insurance/prion-disease/': ["Prion disease is one of the most severe conditions", "!!! READ THIS FIRST !!! Most life insurance companies", "If you or a member of your family has"],
  '/burial-insurance/prostate-cancer/': ["Getting burial insurance with prostate cancer depends heavily on your"],
  '/burial-insurance/ptsd/': ["Burial insurance with PTSD is more available than most"],
  '/burial-insurance/respiratory-lung-conditions/': ["Getting burial insurance with respiratory and lung conditions depends"],
  '/burial-insurance/sarcoidosis/': ["Getting burial insurance with sarcoidosis depends on how serious"],
  '/burial-insurance/sarcoma/': ["Getting burial insurance with sarcoma depends almost entirely on"],
  '/burial-insurance/scams/': ["Burial insurance scams usually come down to confusion and"],
  '/burial-insurance/schizophrenia/': ["Burial insurance with schizophrenia is more available than most"],
  '/burial-insurance/scleroderma/': ["Burial insurance with scleroderma is more available than most"],
  '/burial-insurance/sickle-cell-anemia/': ["Burial insurance with sickle cell anemia depends heavily on severity,"],
  '/burial-insurance/sister/': ["Burial insurance for a sister is possible, but there"],
  '/burial-insurance/skin-cancer/': ["Getting burial insurance with skin cancer depends on the"],
  '/burial-insurance/sleep-apnea/': ["Burial insurance with sleep apnea is more flexible than most"],
  '/burial-insurance/state-regulated-life-insurance/': ["State regulated life insurance is just a marketing phrase,"],
  '/burial-insurance/stent/': ["Getting burial insurance after a heart stent is very doable,"],
  '/burial-insurance/stroke-tia/': ["Getting burial insurance after a stroke or TIA depends"],
  '/burial-insurance/terminal-illness/': ["Burial insurance with a terminal illness is limited but still"],
  '/burial-insurance/terminally-ill-patients/': ["Getting burial insurance for terminally ill patients is possible, but"],
  '/burial-insurance/testicular-cancer/': ["Getting burial insurance with testicular cancer depends heavily on"],
  '/burial-insurance/thyroid-cancer/': ["Getting burial insurance with thyroid cancer depends on the type,"],
  '/burial-insurance/toileting-activities-of-daily-living-adl/': ["Burial insurance with help for toileting ADL is one", "!!! READ THIS FIRST !!! If you need help", "Here’s a detailed guide on what you need to"],
  '/burial-insurance/top-10-final-expense-life-insurance-companies/': ["There’s no single “top 10 final expense life insurance companies”"],
  '/burial-insurance/transferring-activities-of-daily-living-adl/': ["Transferring means moving yourself between your bed, a chair,", "Burial insurance if you need help with transferring or any"],
  '/burial-insurance/traumatic-brain-injury-tbi/': ["Burial insurance with traumatic brain injury depends on how"],
  '/burial-insurance/valvular-heart-disease/': ["Burial insurance with valvular heart disease depends on how"],
  '/burial-insurance/veterans/': ["Burial insurance for veterans fills the gap that VA"],
  '/burial-insurance/wheelchair-users/': ["Being in a wheelchair matters to insurance companies, but"],
  '/burial-insurance/with-first-day-coverage/': ["Burial insurance with first-day coverage is a type of"],
  '/burial-vs-cremation/': ["Burial vs cremation comes down to cost, flexibility, and"],
  '/cancer-insurance/': ["Cancer insurance is a type of optional supplemental health"],
  '/cica-life-burial-insurance-review/': ["CICA Life burial insurance is a type of whole"],
  '/cremation-cost-and-info/': ["Cremation cost and info comes down to one thing,"],
  '/declined-for-life-insurance/': ["Getting declined for life insurance feels like a dead"],
  '/ethos-life-insurance-review/': ["Ethos Life Insurance is an online platform that helps"],
  '/family-benefit-life-burial-insurance-review/': ["Family Benefit Life burial insurance is a type of"],
  '/fidelity-life-burial-insurance-review/': ["Fidelity Life burial insurance is a whole life policy"],
  '/final-expense-life-insurance-complete-guide/': ["Final expense life insurance is a type of whole"],
  '/final-expense-life-insurance-diabetics/': ["Getting final expense life insurance for diabetics is more"],
  '/final-expense-life-insurance-medicaid/': ["Final expense life insurance Medicaid planning is about how"],
  '/final-expense-life-insurance-over-80/': ["Final expense life insurance over 80 is usually your"],
  '/final-expense-life-insurance-pre-existing-conditions/': ["Getting final expense life insurance with pre-existing conditions is"],
  '/final-expense-life-insurance-retired-truckers/': ["Final expense life insurance for retired truckers is usually easier"],
  '/flameless-cremation-burial-insurance/': ["Flameless cremation burial insurance is simply burial insurance used"],
  '/foresters-burial-insurance-review/': ["Foresters burial insurance is a type of whole life"],
  '/funeral-plan-insurance-policies/': ["Funeral plan insurance policies are a type of whole"],
  '/gerber-life-insurance-review/': ["Gerber Life Insurance is known for simple approval and"],
  '/globe-life-price-increase/': ["Globe Life insurance often starts with a low monthly"],
  '/great-western-burial-insurance-review/': ["Great Western burial insurance used to offer whole life"],
  '/guarantee-trust-life-insurance-review/': ["Guarantee Trust Life burial insurance is a whole life"],
  '/how-much-burial-insurance-do-i-need/': ["How much burial insurance you need depends on what"],
  '/how-much-does-a-funeral-cost/': ["Funeral costs can easily reach thousands of dollars, and"],
  '/iul-book/iul-military-members-veterans/': ["Indexed universal life insurance for military members and veterans"],
  '/iul-book/iul-police-officers-firefighters/': ["Indexed Universal Life insurance sounds like a smart mix"],
  '/iul-book/iuls-for-truckers/': ["IULs for truckers sound attractive because they mix life"],
  '/iul-book/teachers-indexed-universal-life-iul/': ["Indexed universal life insurance for teachers sounds appealing, especially"],
  '/liberty-bankers-burial-insurance-review/': ["Liberty Bankers’ burial insurance is a type of whole"],
  '/life-insurance-for-employees/': ["Life insurance for employees is usually called group life"],
  '/life-insurance-for-hiv-positive/': ["Getting life insurance for HIV positive individuals is possible"],
  '/life-insurance-height-weight-guidelines/': ["Life insurance height and weight guidelines are used to"],
  '/life-insurance-savings-group-review/': ["Life Insurance Savings Group is a marketing name, not"],
  '/lincoln-heritage-funeral-advantage-review-old/': ["Lincoln Heritage Funeral Advantage is a type of whole"],
  '/lions-club-member-life-insurance/': ["Lions Club member life insurance isn’t a special policy;"],
  '/lumico-burial-insurance-review/': ["Lumico burial insurance is a type of whole life"],
  '/medicaid-spend-down-rules-on-life-insurance/': ["Medicaid spend-down rules for life insurance determine whether your"],
  '/open-care-life-insurance-review/': ["Open Care life insurance is a marketing platform that"],
  '/oxford-life-burial-insurance-review/': ["Oxford Life burial insurance is a type of whole"],
  '/pay-for-a-funeral-without-life-insurance/': ["If you die without life insurance, your family is"],
  '/phoenix-life-burial-insurance-review-pros-cons/': ["Phoenix Life burial insurance, now part of Nassau Re,"],
  '/prepaid-caskets-pros-and-cons/': ["Prepaid caskets are part of a prepaid funeral plan"],
  '/prepaid-funeral/': ["Prepaid funeral plans let you pay a funeral home"],
  '/primerica-life-insurance-review/': ["Primerica life insurance focuses almost entirely on term life"],
  '/prosperity-life-burial-insurance-review-pros-cons/': ["Prosperity Life burial insurance is a type of whole"],
  '/rapture-life-insurance/': ["Rapture life insurance isn’t an actual type of policy"],
  '/royal-neighbors-of-america/': ["Royal Neighbors of America sells a burial insurance policy"],
  '/senior-legacy-life-review/': ["Senior Legacy Life insurance is not actually selling you"],
  '/senior-life-insurance-review/': ["Senior Life Insurance is a final-expense whole-life insurance company"],
  '/state-farm/': ["State Farm sells a guaranteed issue burial insurance policy"],
  '/term-life-conversion-to-whole-life/': ["Term life conversion to whole life lets you convert a"],
  '/term-life-insurance-doctors/': ["Term life insurance for doctors needs to match income,"],
  '/term-life-insurance-guide-everyone/': ["Term life insurance is the simplest type of life"],
  '/term-life-insurance-truckers/': ["Term life insurance for truckers is usually the smartest"],
  '/the-importance-of-burial-insurance/': ["Burial insurance exists for one reason. To keep your"],
  '/transamerica-burial-insurance-review/': ["Transamerica burial insurance can work, but only in the"],
  '/trinity-life-insurance-review/': ["Trinity Life Insurance focuses heavily on final expense life"],
  '/trustage-life-insurance-review/': ["TruStage life insurance is designed to be simple and"],
  '/trustage-price-increase/': ["TruStage price increases are built into how their term"],
  '/united-heritage-burial-insurance-review/': ["United Heritage burial insurance is a whole life policy"],
  '/valife/': ["VALife sells a burial insurance policy that’s often a"],
  '/veterans-of-foreign-wars-vfw-life-insurance-options/': ["VFW life insurance options sound helpful, but what comes"],
  '/what-happens-when-your-spouse-died-no-life-insurance/': ["When your spouse dies without life insurance, the financial"],
  '/what-is-burial-insurance/': ["Burial insurance is a type of whole life insurance"],
  '/what-to-do-when-a-loved-one-dies/': ["When a loved one dies, there are immediate steps"],
};
