// Article pages deliberately shipped without part of the opening summary
// (src/components/article/ArticleSummary.astro). The article route checks
// every page in src/config/article-pages.ts at build time: a page without a
// Quick Answer, or without its key-points list ("Here’s What This Means for
// You:"), fails the build unless it is listed here with the reason. A listed
// page that has the element fails too, so a hold is removed with its fix.
// The A–Z hubs use a guide summary instead (src/config/hub-nav.ts).

/** No Quick Answer yet. The FLAG pages of the October 2026 Quick Answer audit:
 * the article contradicts itself on its main question, so a faithful answer
 * needs Randy to resolve the conflict first (CLAUDE.md, "Quick Answers"). */
export const QUICK_ANSWER_HELD: Record<string, string> = {
  "/aetna-burial-insurance-review/":
    "The page contradicts itself on the central question of whether most applicants get Aetna’s first-day plan (intro: most don’t qualify; Bottom Line and “Fine Print” section: most do; Pros/Cons: only healthy people qualify) and on pricing (intro: not the cheapest; body: competitive). Any answer to “is Aetna good / will I get day-one coverage” requires picking a side. The proposed answer avoids both and only states plan mechanics.",
  "/baltimore-life-burial-insurance-review/":
    "The page contradicts itself on the points a Quick Answer would lead with: price (more expensive vs average vs not expensive), whether there is any reduced-benefit period (Silver Guard II graded schedule vs FAQ “does not have a waiting period”), coverage size (Silver Guard maximums of $15,000–$25,000 vs FAQ minimum $50,000 and up to $1,000,000), and financial rating (A- vs B++). The FAQ appears to be generic text that doesn’t match the article.",
  "/burial-insurance-defibrillator/":
    "The central question is what happens if the defibrillator was implanted within the last 2 years. The Bottom Line says that limits you to guaranteed issue; the body says a preferred company offers first-day coverage if you haven’t been hospitalized twice in two years. The page also calls a defibrillator both a “serious cardiac risk” and “a minor bump in the road”. A Quick Answer can’t be written without choosing one.",
  "/burial-insurance-diabetic-complications/":
    "The intro and Bottom Line are written only about diabetic amputation and make timing (recent surgery) the deciding factor, while the page covers all diabetic complications and its amputation section makes ADL independence the deciding factor. The page also says a diabetic coma in the last two years still qualifies for first-day coverage while quoting an application question that screens for diabetic coma in the past 2 years. A faithful Quick Answer needs an editorial decision about the intro’s scope and the amputation/coma guidance.",
  "/burial-insurance-kidney-failure/":
    "Direct contradiction on the main question: the intro and Bottom Line say dialysis/kidney failure usually means guaranteed issue only with a 2-year wait, while the body says people on dialysis who follow treatment can often get day-one coverage (and shows a first-day rate for a dialysis patient). This is exactly the kind of conflict that decides the Quick Answer.",
  "/burial-insurance-substance-abuse-drug-abuse/":
    "The page conflicts on what someone with current use or recent treatment can get (a phased-in “first-day benefit plan” vs guaranteed issue only vs no coverage while hospitalized/in rehab) and on the sobriety window (18–24 months vs two years vs two to five years). The proposed answer avoids these by stating only the timing principle, the two-year first-day statement, and the honesty warning; Randy should decide the current-use/recent-treatment guidance before a fuller answer is written.",
  "/burial-insurance/afib/":
    "The central question (who gets first-day coverage) conflicts: the intro and Bottom Line tie immediate coverage to years of stability and say only “some companies may” offer it, while Key Insights/FAQ say most controlled AFib qualifies for Level and insurers focus on control rather than how long you’ve had AFib. The answer adopts the Key Insights side.",
  "/burial-insurance/aids-hiv/":
    "The intro and Bottom Line say well-managed HIV (stable treatment, undetectable viral load) opens up better options, including term and whole life. The body says every insurer imposes a mandatory 2-year waiting period and that you will not qualify for first-day coverage. That changes the core answer.",
  "/burial-insurance/alcohol-or-drug-abuse/":
    "The intro and Bottom Line say most companies want 2 to 3 years of sobriety; the Key Insights and FAQ say 24 months is the standard. The page also says recent treatment usually means guaranteed issue only, while its table (1–2 years sober = graded) and Sarah’s story (inpatient treatment 14 months ago, graded plan) say otherwise. The sobriety window is the heart of the Quick Answer, so Randy needs to choose. The proposed answer avoids both conflicts.",
  "/burial-insurance/and-coronavirus/":
    "The core answers (whether policies exclude pandemics, whether COVID counts as a pre-existing condition, whether it affects rates, and what happens if you are currently sick) are stated in opposite ways in different sections; a Quick Answer would have to pick sides.",
  "/burial-insurance/and-suicide/":
    "The answer’s core claim (burial insurance usually does pay for suicide after the waiting period) is directly contradicted by an FAQ answer that says suicide is typically not covered (likely a source error, but it is on the page and concerns the central question); another FAQ says beneficiaries generally receive the benefit for suicide while the policy is active, with no clause limit.",
  "/burial-insurance/aneurysm/":
    "The page’s central question is timing/eligibility for first-day coverage, and it gives conflicting rules: a hard 24-month cutoff (Key Insights), 6–24 months (Bottom Line), and an untreated aneurysm diagnosed 18 months ago getting day-1 coverage (Sarah; FAQ on monitored aneurysms). The answer’s “stable for a while” dodges the number, and its “recent, untreated … likely … waiting periods” takes one side against the FAQ/story.",
  "/burial-insurance/angina/":
    "The answer says most carriers give first-day coverage after 24 symptom-free months, but the page conflicts on a central eligibility factor: Key Insights says long-acting nitrates (Isosorbide) usually limit you to graded/GI plans, while the FAQ calls Isosorbide a positive sign that helps you get lower premiums; another section says controlled angina qualifies for immediate level coverage with no time condition, and an FAQ points to 12 to 24 months.",
  "/burial-insurance/basal-cell-squamous-cell-carcinoma/":
    "The page contradicts itself on two points a typical Quick Answer would cover: whether recurring skin cancers raise costs/limit options (intro, Bottom Line) or still get Level coverage with no waiting period (Key Insights, table, FAQs), and whether an active, untreated lesion blocks first-day coverage (Key Insights, basal FAQ) or not (squamous FAQ). The proposed answer avoids both points; Randy should resolve them before the answer is expanded.",
  "/burial-insurance/bathing-disability-adl/":
    "Whether first-day coverage is possible is the core of the Quick Answer. The intro and Bottom Line say some people can still get first-day/immediate coverage; the body says no carrier will offer it and guaranteed issue with a 2-year wait is the only option. A Quick Answer would have to pick one.",
  "/burial-insurance/blood-cancer-leukemia/":
    "The page disagrees on what remission means for eligibility: the intro and Bottom Line say 2+ years of remission can unlock immediate coverage, while Key Insights, the policy-type section and Linda’s story say remission is still treated as having cancer and first-day coverage needs being “cured”. The CLL FAQ adds that untreated watch-and-wait CLL can often get first-day coverage. The usual “2 years of remission” line in a Quick Answer would pick a side, so the proposed answer leaves it out.",
  "/burial-insurance/blood-clot/":
    "For a recent clot or someone still on treatment, the intro says to expect higher costs or a waiting period, while the body says clots treated with medication can get first-day coverage with some companies, only a recent thrombectomy is an issue, and maintenance blood thinners are viewed favorably. The 12–24-month section also promises a “first-day benefit plan” whose “death benefit will be phased in over time” (a graded plan described as first-day). A full Quick Answer would have to choose; the proposed answer covers only the uncontested over-24-months case.",
  "/burial-insurance/brain-cancer/":
    "Intro says active or recent cancer means guaranteed issue and immediate coverage only after a few years of remission; Key Insights, policy types, table and Sharon’s story say a doctor-declared cure gets first-day coverage (CICA) before two years.",
  "/burial-insurance/brother/":
    "The page materially contradicts itself on whether you can insure a brother whose health won’t qualify (the answer’s GI sentence picks one side) and on who owns the policy; both go to the central ‘can you get it on your brother’ question.",
  "/burial-insurance/burial-insurance-with-diverticulitis/":
    "The intro, Bottom Line and body say severe cases or recent flare-ups/hospitalizations can raise costs, push you into waiting-period plans, or lead to denial; the FAQ says you cannot be denied, rates are not affected, and there is no waiting period. A complete Quick Answer must say what happens in severe/recent cases, and the page gives opposite answers. The proposed text avoids the conflict by covering only stable and post-surgery cases; Randy should decide the severe-case wording.",
  "/burial-insurance/chronic-bronchitis/":
    "Oxygen outcome is contradictory and the answer picks a side: intro says oxygen may push you into guaranteed issue; the oxygen FAQ says most insurers move oxygen users into a Graded plan; Key Insights even says carriers expanded immediate coverage for controlled oxygen use. Hospitalization outcome also conflicts (graded/2-year wait vs postponement). The answer also turns “these carriers” (Aflac, CICA) into “some carriers”.",
  "/burial-insurance/congestive-heart-failure/":
    "What happens after a recent CHF hospitalization/diagnosis conflicts across the page (guaranteed issue vs graded/modified vs postponement), and the answer states both “most companies push you into guaranteed issue” and “most carriers will offer a graded or modified plan”. How widely first-day coverage is available also conflicts (CICA “the only carrier” vs “most standard companies” after 24 months), while nearly every listed carrier question is a Decline for any CHF history.",
  "/burial-insurance/continence-activities-of-daily-living-adl/":
    "Answer takes the body’s absolute position (“you will not qualify”, “only option”), while the intro and Bottom Line hedge it (“In most cases”, “often the only option”, “decline or limit coverage”). Whether any non-guaranteed-issue option exists is the page’s central question, so the answer picks a side.",
  "/burial-insurance/coronary-artery-disease/":
    "Same conflict as the VERIFY example: intro says a recent event pushes you into guaranteed issue, while the FAQ/table/Linda’s story put a recent procedure or heart event in a graded plan, and another line says recent hospitalizations trigger postponement. The answer states both the graded and the guaranteed-issue outcome for “recent”, leaving the reader with contradictory guidance. First-day lookback also varies (12–24 months vs 24 months).",
  "/burial-insurance/crohns-disease/":
    "The body says surgery in the last 24 months means waiting two years for a level plan, and some findings mean decline by every traditional company; the intro says active or severe cases mean higher costs or longer waits. The FAQ says you cannot be denied or rejected and can still get first-day coverage after surgery, and that Crohn’s won’t affect rates. A complete Quick Answer must say what happens with recent surgery or severe disease, and the page gives opposite answers. The proposed text covers only stable cases; Randy should decide the severe/surgery wording.",
  "/burial-insurance/dementia-alzheimers/":
    "Answer uses the intro’s “Most companies won’t offer first-day coverage”, but the body says first-day coverage is impossible and only guaranteed issue is available (Level and Graded “not an option for anyone with a memory loss diagnosis”), while the carrier list labels a dementia question “Graded” and “Level”. Whether any non-guaranteed-issue option exists after diagnosis is the central question; the answer picks the hedged side.",
  "/burial-insurance/diabetic-insulin-shock/":
    "The answer must say what happens when the insulin shock was within the last 2 years. The intro and Bottom Line say recent episodes usually/almost always mean guaranteed issue or 2-year waiting-period plans (or decline), while Key Insights says CICA Life often gives first-day coverage for recent events and the table lists “Graded / CICA, 0 to 24 Months”, with guaranteed issue only for severe comorbidities. Choosing between first-day coverage and a 2-year wait for recent cases is a material conflict.",
  "/burial-insurance/diabetic-neuropathy/":
    "The core answer is whether stable neuropathy treated with the usual drugs gets first-day coverage. The table puts “Neuropathy (Gabapentin)” in Graded/Modified with a 12–24 month wait, while the FAQ and James’s story say Gabapentin/Lyrica users with no severe complications can often get immediate benefits. The page also says CICA is “one of the only” first-day options and underwriting has tightened, yet elsewhere that “many companies” offer first-day coverage. Since the page calls Gabapentin and Lyrica the most common treatments, these claims materially change the answer.",
  "/burial-insurance/dialysis-patients/":
    "Textbook conflict: the intro and Bottom Line say dialysis usually means guaranteed issue only with a 2-year wait, while body sections, the pricing example and the FAQ say dialysis patients can get first-day coverage. A Quick Answer can’t state the coverage outcome without picking a side.",
  "/burial-insurance/disability/":
    "The key distinction for this topic is whether a waiting period applies. The body says disabilities involving ADL help (and cancer within 2 years) mean guaranteed issue with a two-year wait, but the FAQ flatly says there is no waiting period for disabled applicants. The intro also says the law prevents anyone from denying coverage for a disability, while the SSDI section says traditional carriers flat out decline people on disability benefits. A faithful answer would have to choose between these.",
  "/burial-insurance/down-syndrome/":
    "Answer takes the body’s absolute position (no company offers first-day coverage; guaranteed issue is the only plan), while the intro hedges (“often include a 2-year waiting period”, “assuming all companies treat this the same”) and the Bottom Line says companies decline or limit coverage. Also, the “Plans to avoid” table lists no-health-question 2-year-wait policies, the very plan recommended. Central question.",
  "/burial-insurance/drug-abuse-treatment/":
    "The answer hinges on what recent-treatment applicants get. The intro says most companies decline and push you to guaranteed issue, and the FAQ says no first-day coverage until 2+ years sober, but the “within the last 2 years” section says you “will qualify for a first-day benefit plan” (described as first-day coverage with a phased-in benefit, i.e. graded). The sober threshold also varies: “two to five years” vs “easily qualify” after two years.",
  "/burial-insurance/drug-alcohol-abuse/":
    "The sobriety timeline is the page’s central factor and it conflicts: the answer says 2 years typically qualifies for first-day level plans (Key Insights), but the intro and Bottom Line say 2–3 years and only “may qualify”, and another section says controlled abuse is “still a big issue” for first-day coverage.",
  "/burial-insurance/dui-dwi/":
    "The intro and Bottom Line say a recent DUI can mean denial/postponement, older DUIs mean higher premiums, and multiple DUIs can mean guaranteed issue; the body and FAQ say carriers that don’t ask will give first-day coverage at the lowest rate, with no waiting period and possibly no rate impact, even for several DUIs. The FAQ also contradicts itself on whether a DUI must be disclosed. The Quick Answer would have to choose between these.",
  "/burial-insurance/eating-activities-of-daily-living-adl/":
    "Answer takes the body’s absolute position (“won’t qualify”, “only option”), while the intro and Bottom Line hedge it (“usually in guaranteed issue form”, “decline you or limit coverage heavily”) and the underwriting section says help with eating is “generally a decline”. Whether any non-guaranteed-issue option exists is the central question.",
  "/burial-insurance/endocarditis-heart-infection/":
    "The key timing for first-day coverage conflicts: Key Insights and the table say 12 months of recovery opens level coverage, while two FAQs say 24 months. The plan for recent treatment also conflicts: the intro says guaranteed issue, the table says graded. The proposed answer avoids both by giving no month threshold and covering only the consistent active-infection rule, but a useful answer would normally include the threshold, which needs Randy’s decision.",
  "/burial-insurance/fatty-liver-disease/":
    "For the main case (simple nonalcoholic fatty liver), the intro says mild, controlled cases can get immediate coverage and the FAQ says there is no waiting period, but the body’s recommendation is a “first-day benefit plan” whose death benefit is “phased in over time” (a graded benefit). Cirrhosis gets the same recommendation as simple NAFLD, and recent alcohol-related cases get guaranteed issue, contradicting the FAQ’s “no waiting period”. Whether the benefit is full from day one is the core of the answer.",
  "/burial-insurance/final-expense-life-insurance-dave-ramsey/":
    "The page’s verdict conflicts: the intro and Bottom Line present Ramsey’s critique approvingly (final expense gives small coverage at a higher cost; you can overpay for a policy that barely covers final expenses), while the body argues Ramsey is wrong for seniors and final expense fills the gap he overlooks. A normal Quick Answer would state the page’s conclusion, which is an editorial choice. The proposed answer stays descriptive and avoids a verdict; Randy should confirm the intended stance (and likely align the intro and Bottom Line with the body).",
  "/burial-insurance/for-smokers/":
    "The answer’s absolute claims are contradicted elsewhere on the page: higher premiums for smokers (“every insurance company”) vs the FAQ “not all life insurance companies charge smokers more”; “even one … cigar” in 12 months = smoker vs a quoted question that excludes occasional pipe/cigar use and chewing-tobacco exception; FAQ says some companies won’t issue a policy until you stop smoking, while the body offers first-day smoker-rate plans. These go to the page’s central question (whether and at what rate smokers get coverage).",
  "/burial-insurance/graves-disease/":
    "One passage: Graves’ disease “on its own will not create an issue”; another: some companies deny or add a waiting period because of standard Graves’ medications.",
  "/burial-insurance/guaranteed-issue-life-insurance-for-seniors/":
    "The page’s defining feature is stated both ways: “Most” GI plans have the 2-year waiting period (intro, Bottom Line, waiting-period section) vs “all” GI policies carry it and it is “mandatory” (body, pricing section, FAQ). The answer picks “most plans”, implying some GI plans have no wait, which other sections deny; the accidental-death rule has the same most/all split. Central to “what is guaranteed issue”.",
  "/burial-insurance/high-blood-pressure/":
    "The page (H1 “Burial Insurance With Uncontrolled High Blood Pressure”) gives opposite answers for the uncontrolled case: the intro says unstable blood pressure will likely push you into guaranteed issue, while the body says people with uncontrolled high blood pressure often qualify for first-day coverage if they take their medication, with guaranteed issue only after 2+ hospitalizations in 2 years. A Quick Answer has to choose one, so it needs Randy’s decision. The intro’s mention of term life also doesn’t match the body.",
  "/burial-insurance/hospice-patients/":
    "Answer states the body’s absolute position (no company offers first-day coverage; GI is the only option), but the intro and Bottom Line, the page’s own summaries, say most traditional policies decline and coverage is usually/often guaranteed issue. Whether any non-GI option exists is the page’s central question, so the answer picks one side.",
  "/burial-insurance/huntingtons-disease/":
    "The page can’t settle what a diagnosed applicant can get. One section says controlled Huntington’s qualifies for immediate level coverage and most seniors will have no trouble getting an instant-approval policy. The FAQ says immediate coverage is rarely available once symptoms show and that a graded plan is the reality for most. The intro says guaranteed issue is the main option. Its own table puts “Early Stage / Stable” in Graded. Choosing between first-day, graded and guaranteed issue needs Randy’s call.",
  "/burial-insurance/insulin-diabetics/":
    "The intro says diabetes complications will likely push you into guaranteed issue with a 2-year wait. The body says complications such as neuropathy, retinopathy, even nephropathy with dialysis, and recent insulin shock or diabetic coma can still get first-day coverage with the right company. Complications are central to this topic, so a full Quick Answer has to pick a side. The proposed answer leaves complications out to avoid the conflict, but Randy should decide which statement is correct.",
  "/burial-insurance/leukemia/":
    "The core timing answer conflicts: the intro and most of the body say 2 years cancer-free opens first-day coverage, but the treatment section says first-day coverage needs at least three years of remission. The body also says you “will qualify” at 2 years (level benefit) while the intro says only “some insurers”, and the remission section says 2 years of remission gets only a phased-in (graded) benefit. Any Quick Answer must pick a timeline and a strength, so Randy needs to decide.",
  "/burial-insurance/lou-gehrigs-disease-als/":
    "The page contradicts itself on the central question. It says first-day coverage is impossible for ALS (and that anyone promising it is lying), but also says controlled ALS qualifies for immediate level coverage and that the case stories show “day-one protection”. It also disagrees on the fallback: graded plans that pay part of the benefit sooner versus a two-year waiting period on “all policies”. Randy needs to remove the template sentences that don’t fit ALS before a Quick Answer can be written.",
  "/burial-insurance/lung-cancer/":
    "Whether remission counts as active cancer is the heart of the Quick Answer, and the page says both that most companies treat remission as active cancer and that survivors in remission two years can often get first-day coverage. It also says “controlled lung cancer” qualifies for immediate level coverage, and Linda’s story gives first-day coverage soon after a recent diagnosis, while the table puts remission under 2 years in a graded plan. The intro’s “a few years” also differs from the two-year milestone.",
  "/burial-insurance/lung-disease/":
    "Answer says advanced or unstable lung disease likely means guaranteed issue. The page gives three different outcomes for recent hospital stays/instability (GI in intro, graded plan in FAQ, postponement in underwriting section), which is central to what coverage you can get.",
  "/burial-insurance/lupus/":
    "The intro, its CTA line and all six Bottom Line bullets are about TruStage term-life price increases, not lupus (they appear to come from a TruStage article). The lupus body is internally consistent, and the proposed answer is built only from it, but the page needs an editorial fix: the intro and Bottom Line must be replaced before the Quick Answer goes live.",
  "/burial-insurance/melanoma-skin-cancer/":
    "Answer takes the body’s absolute claims (“easily qualify”; “can’t avoid a waiting period”). The intro and Bottom Line are materially softer on both branches (may qualify; most companies limit you to a waiting period OR higher costs; recent treatment “often” means a waiting period), and two sample questions use 3-year look-backs vs the stated 2-year look-back. These are the page’s central timing outcomes.",
  "/burial-insurance/multiple-myeloma/":
    "Maintenance therapy is common with myeloma, and the page gives three incompatible answers for it: carriers “will always” put you in a two-year waiting-period plan, a graded plan is the usual choice, and Robert got a level first-day plan while on maintenance Revlimid (with maintenance described as “a sign of success”). The proposed answer uses only the intro and avoids the maintenance question, but Randy should resolve which rule is correct before publishing.",
  "/burial-insurance/muscular-dystrophy/":
    "Answer says GI is the “only option” for wheelchair users or those needing ADL help. The intro and the ADL section itself say “most companies will decline you”, and home health care says “only a few companies accept”; FAQ says “Some insurers” have a two-year wait. Whether any non-GI option exists is central to the page’s question.",
  "/burial-insurance/myelodysplastic-syndrome/":
    "The intro and Bottom Line treat MDS like a blood cancer (guaranteed issue within 2 years of diagnosis or treatment; immediate coverage only after being cancer-free for 2 years, and a 2-year wait “usually”). The body says controlled MDS qualifies “most people” for immediate level coverage, including people on maintenance medication, as long as counts are stable. These lead to opposite Quick Answers for a typical person living with MDS on treatment, so Randy needs to decide which is right.",
  "/burial-insurance/native-americans/":
    "The intro and Bottom Line say there is no special life insurance for Native Americans, but several FAQ answers say many companies offer policies “specifically tailored” or “specifically designed” for Native Americans, and the best-option section ties the recommendation to tribal membership. The proposed answer avoids that question, but the FAQ needs an editorial fix so the page doesn’t contradict itself.",
  "/burial-insurance/need-help-with-dressing-activities-of-daily-living-adl/":
    "Answer states the body’s absolute (“won’t qualify for first-day”, GI is the “only plan”). The intro and Bottom Line say “most companies” limit you to GI/waiting-period plans and severe limitations “often” lead to GI only; the body also says ADL applicants “have a short waiting period”. This is the page’s central question.",
  "/burial-insurance/neurological-disorders/":
    "ADL outcome conflicts: intro “most companies will only offer” GI vs key insight/policy types “will require”/“only option” GI vs Bottom Line “usually blocks first-day” vs MS FAQ “modified plan”. Answer also says dementia/Alzheimer’s “always” require GI while the FAQ says insurers “almost always” require a waiting period. The answer picks sides on central coverage outcomes.",
  "/burial-insurance/nursing-home-residents/":
    "The page both names guaranteed issue as the best/only option and says it is a terrible choice it doesn’t recommend; it also says “most” residents won’t qualify for traditional coverage vs. guaranteed issue being the “only option”. A Quick Answer that recommends (or rules out) a plan type, or says whether anything besides guaranteed issue is possible, would have to pick a side. The proposed answer avoids those points; Randy should decide the page’s recommendation.",
  "/burial-insurance/organ-transplant/":
    "The intro and Bottom Line say stable transplant recipients can later qualify for better coverage (term, standard whole life, approval after 1–3 years), while the body says guaranteed issue is the only option for any transplant recipient, ever; another line promises an instant-approval policy for most people. The core answer (is anything besides guaranteed issue possible?) can’t be written without choosing.",
  "/burial-insurance/overweight-obese/":
    "Whether weight itself raises your price is a natural part of this Quick Answer, but the intro and Bottom Line say higher BMI usually means higher rates while the body and FAQ say weight has no effect on premiums and morbidly obese applicants can get the best rates. The proposed answer leaves pricing out; Randy should resolve which statement is correct.",
  "/burial-insurance/oxygen-use/":
    "The intro and FAQ say first-day coverage is extremely rare and most oxygen users get only guaranteed issue (sleep apnea the only real exception), while other sections say controlled oxygen use qualifies most people for immediate level coverage and that temporary past use often qualifies. The table puts current users in a graded plan, not guaranteed issue. The core answer (first-day possible or not; GI vs graded) can’t be written without choosing.",
  "/burial-insurance/pacemaker/":
    "The key timing threshold differs: the intro says first-day coverage may be possible once surgery is over 6 to 12 months ago, while the body makes 24 months the primary boundary (CICA the one exception) and says surgery in the last 12 months usually means a two-year waiting period. Pending tests are said to mean guaranteed issue only in one place and postponement in another. The Quick Answer’s core timing statement can’t be written without choosing.",
  "/burial-insurance/prostate-cancer/":
    "Central timing question conflicts: Key Insights and underwriting section say after surgical removal insurers/many carriers view you as cancer-free/cured immediately, while the FAQ says most insurers allow immediate payouts only after the two-year milestone following surgery. The answer’s 24-month rule picks one side for the most common treatment path. Also table puts recent treatment in Graded while the answer says GI is typically the only option.",
  "/burial-insurance/sickle-cell-anemia/":
    "Intro: recent hospitalizations “often” mean guaranteed issue; body: any sickle cell hospitalization leaves guaranteed issue as the only option, while also citing 6- and 12-month look-backs.",
  "/burial-insurance/terminally-ill-patients/":
    "The answer’s core claim (“Your only option is guaranteed issue”) picks one side: the intro and Bottom Line hedge it (“usually left with”, “Most people only qualify”), while the body says it is the only option for every terminally ill applicant. The answer also mixes “most people won’t qualify” with “only option”. The page further says “We DO NOT offer insurance plans for anyone with a terminal illness” yet names guaranteed issue the best option, and the intro says early death “often” refunds only premiums vs the body’s definite refund rule.",
  "/burial-insurance/thyroid-cancer/":
    "Timing/eligibility for first-day coverage (the central question) conflicts across the page and the answer picks the Key Insights side: Key Insights say most companies offer first-day coverage after 2 years cured and one carrier at any time; the intro says options improve after 2 to 3 years and you “may” qualify; the FAQ says medullary and anaplastic types typically are restricted to graded/guaranteed issue (the answer’s 2-year claim ignores type); the RAI FAQ and table say a 12–24 month stability period with Standard/Graded coverage; another FAQ puts the lowest rates at 5–10 years.",
  "/burial-insurance/top-10-final-expense-life-insurance-companies/":
    "The page’s direct answer would name companies, but the intro names a different set (Transamerica, Americo aren’t in the ranking) and presents AIG favorably, the list says every company includes first-day coverage while #10 AIG is a 2-year-waiting-period-only plan, and Mutual of Omaha is both a favorite and in the “Fearful 4”. Choosing which companies to name needs Randy’s editorial decision. The proposed answer avoids naming companies.",
  "/burial-insurance/transferring-activities-of-daily-living-adl/":
    "The Bottom Line and the second intro paragraph answer a different question (transferring policy ownership), while the H1 and body are about needing help with the “transferring” activity of daily living. Randy must confirm the page’s question and fix the Bottom Line/intro before a Quick Answer goes live; the proposed answer follows the H1 and body.",
  "/burial-insurance/traumatic-brain-injury-tbi/":
    "What a recent TBI can get is central to the question and the page contradicts itself; the answer takes the intro side (“likely … guaranteed issue”). The Graded policy type says graded is common for recent injuries, the coverage table gives Level (Family Benefit) with no wait to stable applicants with no hospital stay in 1 year, and Linda (14 months, still in therapy) got immediate protection.",
  "/burial-insurance/valvular-heart-disease/":
    "Intro: severe or recent means guaranteed issue; FAQ, table (“Recent Surgery – Graded”) and Mary’s story: recent valve surgery gets a graded plan.",
  "/burial-insurance/wheelchair-users/":
    "For full-time wheelchair users who can do all daily activities and have no chronic illness, the intro and Bottom Line suggest first-day coverage may be possible with a stable condition, while the body says guaranteed issue and the FAQ says a two-year wait is typical. That group is a core audience, and the proposed answer leaves it out rather than pick a side; Randy needs to decide.",
  "/buyers-guide/": "Held by Randy (October 2026).",
  "/cancer-insurance/":
    "The page title asks “Why You Need It”, and the body says everyone needs cancer insurance while the Bottom Line and intro say some people don’t need it. Whether a reader needs it can’t be answered without picking a side; the proposed answer covers only what cancer insurance is.",
  "/cica-life-burial-insurance-review/":
    "For a company-review question (“Is CICA a good choice?”) the page contradicts itself on the company’s service/complaint record and overall verdict: the Bottom Line says customers complain of slow claims and hard-to-reach service and that better carriers offer stronger coverage at similar or lower cost, while the body says CICA’s complaint record is remarkably low (“a great company”) and that it is the only carrier covering so many impairments. The answer avoids the complaint question, which is central to whether the company is a good choice.",
  "/declined-for-life-insurance/":
    "The answer opens by asserting a denial 'isn’t a dead end' (intro), but the page's FAQ on the consequences of a decline says future coverage may be 'difficult or impossible'. This concerns the page's central question (what happens / what can you do after a decline), so the answer picks one side of a material conflict.",
  "/elks-lodge-life-insurance-options/":
    "The page’s core question gets opposite answers: the intro and Bottom Line say the Elks partner with programs offering term, whole life or accident insurance at group rates, while the body and FAQs say the Elks offer no life insurance, have no group plan and do not partner with any insurer. The Quick Answer would have to pick one.",
  "/final-expense-life-insurance-retired-truckers/":
    "Severe conditions (oxygen, kidney failure, advanced COPD, recent cancer/heart events) “always”/“impossible” for first-day coverage in some places, “may”/“typically”/“generally” and graded/modified plans in others.",
  "/flameless-cremation-burial-insurance/":
    "The central answer is uncertain on the page itself: the intro and body say any burial-insurance payout is cash the family can use however they want (no special policy needed), but the FAQs say only “many” providers cover flameless cremation and the beneficiary “may be able to” use the payout. Cost versus traditional cremation is also stated three different ways (price competitive / typically cheaper / sometimes higher), and legality is “sixteen states” vs “legal in most locations”. A faithful answer would have to choose.",
  "/funeral-plan-insurance-policies/":
    "The page defines its own subject two incompatible ways: the intro says a funeral plan insurance policy is whole life insurance paying a lump sum to your family, while the main sections describe it as a prepaid funeral contract paid to a funeral director/provider with prices locked in, and the FAQ says prepaid funerals and funeral insurance are different things. The Quick Answer can’t say what the product is without picking one.",
  "/great-western-burial-insurance-review/":
    "The intro and Bottom Line say Great Western stopped issuing new burial policies in 2024, but the body still presents three products as currently offered, with pricing, same-day approval and “buying Great Western burial insurance is an option”. Whether the product can be bought at all is the core of the Quick Answer.",
  "/how-much-does-final-expense-insurance-cost/":
    "The page’s primary question is a price question, and it gives at least four materially different typical/average monthly costs ($25; $25–$75; $50; $50–$100 for $10,000; Bottom Line $30–$100). A dollar-based Quick Answer would require choosing one. The proposed answer avoids figures and only states the cost factors, which are consistent across the page; Randy should decide which price range (if any) the Quick Answer should quote.",
  "/is-burial-insurance-worth-it/":
    "The page’s primary question is the verdict. The intro (and Bottom Line) frame burial insurance as a narrow fit - mainly for people without savings who can’t qualify for term or traditional whole life, and not the best option for most - while the body concludes flatly “Burial insurance is worth it” for anyone whose death would burden their family and calls it the “best option” in many situations, and calls premiums “incredibly affordable” vs. the intro’s “you pay more per dollar of coverage.” Any Quick Answer would have to pick one verdict.",
  "/life-insurance-for-hiv-positive/":
    "The core answer depends on whether HIV-positive applicants can get regular term/whole life (intro: stable, documented health may qualify) or are limited to guaranteed issue with a mandatory two-year waiting period at every company (IMPORTANT box and “Best Option: Guaranteed issue”). The page also says both that you answer basic health questions and that the best option asks none. A Quick Answer can’t be written without picking a side.",
  "/life-insurance-savings-group-review/":
    "What the company is and sells (central to whether to buy there) conflicts: intro says it is a lead-generation site passing you to agents selling usually term or whole life from a limited set of companies; body says it only sells one AIG guaranteed acceptance plan as a SelectQuote brand. The answer's 'doesn’t let you compare rates and coverage from different companies' and guaranteed-acceptance framing take the body's side. Waiting-period payout is also stated both as nothing and as premiums plus interest.",
  "/lumico-burial-insurance-review/":
    "For 'is Lumico any good', the cost of its only first-day plan (Preferred) is central, and the page contradicts itself: more expensive / better-priced plans available vs. competitively priced and comparable. The answer avoids price, but then cannot reliably say whether the Preferred plan is a good buy; age limits also conflict (50–85 vs 50–80).",
  "/medicaid-spend-down-rules-on-life-insurance/":
    "The page’s core answer is whether a policy’s cash value counts toward Medicaid’s asset limit. The body says permanent-policy cash value counts (above a face-value exemption, usually $1,500) against a $2,000 limit, but the FAQ says cash-value policies are the exception that Medicaid won’t require be used, and that there is no asset limit for Medicaid. These directly contradict the core answer, so a Quick Answer would require choosing between them.",
  "/mutual-of-omaha-burial-insurance/": "Held by Randy (October 2026).",
  "/oxford-life-burial-insurance-review/":
    "The intro and Bottom Line describe graded/2-year waiting-period plans that many applicants end up in, while the body only describes two first-day coverage plans (Assurance and Assurance One) and the FAQ says Oxford has no waiting period. The intro also promises simple approval even with health issues, while the cons say only healthier people qualify. The central answer (what most applicants get) can’t be stated without choosing a side.",
  "/rapture-life-insurance/":
    "The page’s central question is whether a policy pays after a Rapture-style disappearance. The intro and FAQ say no benefit would be paid / the payout would be denied, while the body says the beneficiary would eventually receive the benefit once a court declares the insured presumed dead (and also defines legal proof as requiring a body, which contradicts the presumed-death process). The proposed answer avoids the conflict but Randy should decide which message the page gives.",
  "/security-national-burial-insurance-review/":
    "The page contradicts itself on pricing (central to ‘is it good’) and on whether there is a waiting period at all; also on which plan insulin users get. The answer takes the ‘more expensive’ side.",
  "/senior-legacy-life-review/":
    "The page’s primary question is whether Senior Legacy Life is a real insurer. The intro and body say it is not an insurance company but a lead-generation/marketing brand, while the FAQ answer says “It is a legitimate insurance carrier” (and then says they don’t sell insurance). The FAQ also switches to a different company (Senior Life Insurance Company, Thomasville, Georgia) and its reviews. Any Quick Answer must pick one of these, so Randy needs to correct the FAQ first. Once fixed, an answer could be built from the intro (lead-generation platform; no prices upfront; possible waiting periods).",
  "/senior-legacy-vs-senior-legacy-life/":
    "The page’s primary question is the difference between the two names. The intro and Bottom Line say both are lead-generation/marketing platforms, while the body and verdict say Senior Legacy is a lead vendor and Senior Legacy Life is a licensed insurance agency that sells policies; the FAQ then calls Senior Legacy a sales agency. A Quick Answer that explains the difference must pick one version. The proposed answer avoids the difference and only states what the page agrees on.",
  "/term-life-conversion-to-whole-life/":
    "Cost is the key tradeoff the intro names (“The catch is cost”), but the body says premiums may be 10–15 times higher while the FAQ says you keep paying the same premium and that converting is generally inexpensive. The conversion-deadline window also differs (age 65–70 or first 5–10 years vs usually 10–20 years). A complete Quick Answer needs Randy to settle these; the proposed answer avoids both.",
  "/trustage-life-insurance-review/":
    "Cost is central to whether TruStage is a good choice, and the answer says its products cost more. The FAQ says the opposite (lower premiums), so the answer takes one side of a material conflict.",
  "/trustage-price-increase/":
    "The page’s question is why TruStage prices go up. The body says the increases are built into the term policy’s 5-year age bands, while the FAQ says prices rose for all products because of rising costs (which also contradicts the whole life “Premiums never go up”). The answer picks the age-band explanation.",
  "/united-heritage-burial-insurance-review/":
    "The answer’s main downside is the modified plan’s two-year reduced benefit (premiums plus interest only), but the FAQ answers “Does United Heritage Life have a waiting period?” with a plain “No”. Whether coverage is delayed is central to whether the policy is good.",
  "/veterans-of-foreign-wars-vfw-life-insurance-options/":
    "The intro and Bottom Line present free, accident-only coverage as the main VFW offering (“Most VFW life insurance is accident-only”), while the body and FAQ say membership includes no free life insurance and describe term, final expense and guaranteed-issue plans bought separately. Whether a VFW member has any free coverage is central to the page’s question. The benefit-reduction age also differs (after 75 vs after 70). The proposed answer avoids both points; Randy should decide which is current before the intro/Bottom Line or FAQ is corrected.",
};

/** No key-points list: the article has none to show. */
export const SUMMARY_HELD: Record<string, string> = {
  "/burial-insurance/diabetic-retinopathy/":
    "The article has no key-points list (\"Here’s the Bottom Line\") to show; adding one needs new copy Randy approves.",
  "/burial-insurance/disability/":
    "The article has no key-points list (\"Here’s the Bottom Line\") to show; adding one needs new copy Randy approves.",
  "/buyers-guide/":
    "The article has no key-points list (\"Here’s the Bottom Line\") to show; adding one needs new copy Randy approves.",
};
